server:
  port: 8081


spring:
  redis:
    host: 192.168.2.2
  datasource:
    datasource: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456

Test:
  a: 456