server:
  port: 8080

# logging
logging.config: ./logback.xml
logging.level:
  cn.com.bsfit.portal.mapper: INFO
  com.atomikos: INFO
  jdbc: #SQL相关日志
    audit: ERROR #输出除了ResultSet外的所有JDBC调用情况。一般不需要
    sqlonly: ERROR #只输出SQL，不输出执行时间
    sqltiming: INFO #输出SQL和执行时间 ERROR OR INFO OR DEBUG
    resultset: ERROR #输出返回结果集
    connection: ERROR #输出连接情况
    resultsettable: ERROR #输出执行SQL和结果集

frms:
  workflow:
    kafka:
      kafka-brokers: 192.168.2.2:9092
      compression-type: gzip
      #会话的超时限制，单位毫秒
      session-timeout: 15000
      retries: 0
      production:
        enable: true
        enable-compress: false
        group-id: workflow-engine-application-production
        enable-final-state-delayed-replica: true
        final-state-replica-delay: PT10S
      simulation:
        enable: false
        enable-compress: false
        group-id: workflow-engine-application-simulation
        enable-final-state-delayed-replica: true
        final-state-replica-delay: PT10S
      indicator:
        enable: true

spring:
  redis:
    host: 192.168.2.2
  datasource:
    datasource: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/newboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
Test:
  a: 456