server:
  port: 8081


spring:
  redis:
    host: 192.168.2.2
  datasource:
    datasource: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/newboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
Test:
  a: 456